INSERT INTO clientes (nombre, email, telefono, fecha_nacimiento, genero, direccion, notas, fecha_registro, fecha_actualizacion) VALUES ('María García', 'maria.garcia@email.com', '987654321', '1990-05-15', 'femenino', 'Av. Principal 123, Lima', 'Cliente frecuente, prefiere cortes modernos', NOW(), NOW());
INSERT INTO clientes (nombre, email, telefono, fecha_nacimiento, genero, direccion, notas, fecha_registro, fecha_actualizacion) VALUES ('Ana López', 'ana.lopez@email.com', '987654322', '1985-08-22', 'femenino', 'Jr. Los Olivos 456, Lima', 'Cliente VIP, alergica a ciertos productos', NOW(), NOW());
INSERT INTO clientes (nombre, email, telefono, fecha_nacimiento, genero, direccion, notas, fecha_registro, fecha_actualizacion) VALUES ('Carlos Mendoza', 'carlos.mendoza@email.com', '987654323', '1992-11-30', 'masculino', 'Calle Lima 789, Callao', 'Prefiere citas por la tarde', NOW(), NOW());
INSERT INTO clientes (nombre, email, telefono, fecha_nacimiento, genero, direccion, notas, fecha_registro, fecha_actualizacion) VALUES ('Laura Torres', 'laura.torres@email.com', '987654324', '1988-03-10', 'femenino', 'Av. Arequipa 321, Lima', NULL, NOW(), NOW());
INSERT INTO clientes (nombre, email, telefono, fecha_nacimiento, genero, direccion, notas, fecha_registro, fecha_actualizacion) VALUES ('Roberto Díaz', 'roberto.diaz@email.com', '987654325', '1995-07-18', 'masculino', 'Jr. Huancayo 654, Lima', 'Cliente nuevo, referido por María', NOW(), NOW());

INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Shampoo Hidratante', 'Shampoo profesional para todo tipo de cabello', 'L''Oréal', 'Cuidado Capilar', 50, 10, 25.99, 'Distribuidora Beauty Pro', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Acondicionador Nutritivo', 'Acondicionador reparador intensivo', 'Pantene', 'Cuidado Capilar', 45, 10, 22.50, 'Distribuidora Beauty Pro', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Tinte Profesional Negro', 'Tinte permanente color negro intenso', 'Wella', 'Coloración', 30, 8, 35.00, 'Colorex SAC', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Tinte Profesional Castaño', 'Tinte permanente color castaño natural', 'Wella', 'Coloración', 28, 8, 35.00, 'Colorex SAC', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Gel Fijador Extra Fuerte', 'Gel para peinado con fijación extrema', 'Schwarzkopf', 'Estilizado', 60, 15, 18.90, 'Distribuidora Beauty Pro', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Crema Alisadora', 'Crema para alisado permanente', 'Kerastase', 'Tratamientos', 20, 5, 89.00, 'Premium Hair Products', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Serum Reparador', 'Serum intensivo para puntas dañadas', 'Moroccanoil', 'Tratamientos', 15, 5, 65.00, 'Premium Hair Products', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Spray Protector Térmico', 'Protección contra calor de planchas y secadores', 'TRESemmé', 'Cuidado Capilar', 40, 10, 28.50, 'Distribuidora Beauty Pro', 'disponible', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Mascarilla Capilar', 'Mascarilla intensiva de hidratación profunda', 'Dove', 'Tratamientos', 8, 10, 32.00, 'Distribuidora Beauty Pro', 'agotado', NOW(), NOW());
INSERT INTO productos (nombre, descripcion, marca, categoria, stock, stock_minimo, precio, proveedor, estado, fecha_creacion, fecha_actualizacion) VALUES ('Cera para Cabello', 'Cera modeladora con acabado mate', 'American Crew', 'Estilizado', 35, 8, 42.00, 'Men''s Grooming Store', 'disponible', NOW(), NOW());

INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (1, 'Corte de Cabello Dama', 'Corte profesional para dama con lavado y secado incluido', 45, 35.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (1, 'Corte de Cabello Caballero', 'Corte clásico o moderno para caballero', 30, 25.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (2, 'Tinte Completo', 'Aplicación de tinte en todo el cabello, incluye lavado', 90, 80.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (2, 'Mechas Californianas', 'Aplicación de mechas con técnica balayage', 120, 150.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (3, 'Manicure Clásico', 'Cuidado completo de uñas de manos', 40, 30.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (3, 'Pedicure Spa', 'Tratamiento completo para pies con exfoliación', 60, 45.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (4, 'Keratina Brasileña', 'Tratamiento alisador con queratina natural', 180, 200.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (4, 'Tratamiento Botox Capilar', 'Tratamiento intensivo de reconstrucción capilar', 90, 120.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (5, 'Peinado para Evento', 'Peinado profesional para eventos especiales', 60, 65.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (5, 'Maquillaje Social', 'Maquillaje para eventos diurnos o nocturnos', 45, 55.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (1, 'Lavado y Secado', 'Lavado profesional con productos premium y secado', 30, 20.00, 'activo', NOW(), NOW());
INSERT INTO servicios (id_categoria, nombre, descripcion, duracion_min, precio, estado, fecha_creacion, fecha_actualizacion) VALUES (4, 'Hidratación Profunda', 'Tratamiento de hidratación intensiva con mascarilla', 45, 50.00, 'activo', NOW(), NOW());

INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (1, 1, 1, '2025-12-05 10:00:00', 45, 'confirmada', 'Cliente solicita estilo bob moderno', NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (2, 3, 2, '2025-12-05 14:00:00', 90, 'confirmada', 'Tinte color castaño claro', NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (3, 2, 1, '2025-12-06 09:00:00', 30, 'pendiente', NULL, NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (4, 7, 3, '2025-12-06 15:00:00', 180, 'confirmada', 'Primera vez con keratina, revisar alergias', NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (5, 5, 2, '2025-12-07 11:00:00', 40, 'pendiente', NULL, NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (1, 9, 2, '2025-12-08 16:00:00', 60, 'pendiente', 'Peinado para boda', NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (2, 12, 1, '2025-12-08 10:30:00', 45, 'confirmada', NULL, NOW(), NOW());
INSERT INTO citas (id_cliente, id_servicio, id_user, fecha_hora, duracion_estimada, estado, notas, fecha_creacion, fecha_actualizacion) VALUES (3, 11, 1, '2025-12-09 08:00:00', 30, 'pendiente', NULL, NOW(), NOW());
